# Generated by Django 2.1.1 on 2020-01-15 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20191104_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAdmin2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Post')),
            ],
        ),
    ]
